export const GET_PHOTOS_REQUEST = 'GET_PHOTOS_REQUEST'
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS'
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE' 

export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM'